name: Count CI

on: [push, pull_request, release]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]
        java-version: [1.8]
        build-args: [ "" , "--prod --release" ]
        patch: [ "", "patches/store-release.patch" ]

    steps:
    - uses: actions/checkout@v2

    - name: patch
      run: |
        if [ -f "${{ matrix.patch }}" ]; then
          git apply "${{ matrix.patch }}"
          git diff
        fi

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install
      run: npm install

    - name: install cli tools
      run: |
        npm install -g --no-save \
          @ionic/cli@6.1.0 \
          native-run@0.3.0 \
          cordova@9.0.0 \
          cordova-res@0.8.1

    - name: npm lint
      run: npm run lint

    - name: npm build
      run: npm run build --if-present

    - name: npm test
      run: npm run test-headless

    - name: Coveralls Parallel
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel: true

    - name: Use JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}

    - name: ionic cordova build
      run: |
        ionic \
          cordova build \
            android ${{ matrix.build-args }}
      env:
        CI: true

    - name: Finalize APK
      env:
        STOREPASS: ${{ secrets.ACTIONS_KEYSTORE_PW }}
      run: |
        find platforms/ -name '*.apk' -print0 \
        | xargs -0 -n1 ./apk_finalize.sh

    - name: Upload Artifacts
      uses: actions/upload-artifact@master
      #if: github.event == 'release' && matrix.patch == ''
      if: matrix.patch == ''
      with:
        name: "count-node${{ matrix.node-version }}-jdk${{ matrix.java-version }}"
        path: platforms/android/app/build/outputs

    - name: Upload Artifacts for Store
      uses: actions/upload-artifact@master
      #if: github.event == 'release' && matrix.patch == 'patches/store-release.patch'
      if: matrix.patch == 'patches/store-release.patch'
      with:
        name: "count4store-node${{ matrix.node-version }}-jdk${{ matrix.java-version }}"
        path: platforms/android/app/build/outputs

    - name: Coveralls Finished
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}
        parallel-finished: true
