name: Count CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # node-version: [8.x, 10.x, 12.x]
        node-version: [12.x]
        java-version: [1.8]
        build-args: [ "" , "--prod --release" ]

    steps:
    - uses: actions/checkout@v1
    - name: Use JDK ${{ matrix.java-version }}
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java-version }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, lint, build, and test
      run: |
        npm install
        npm run lint
        #npm run build --if-present
        #npm test
      env:
        CI: true
    - name: ionic cordova build
      run: |
        npm install -g --no-save \
          ionic \
          native-run \
          cordova \
          cordova-res
        ionic cordova build android ${{ matrix.build-args }}
      env:
        CI: true
    - uses: actions/upload-artifact@master
      with:
        name: "count"
        path: platforms/android/app/build/outputs

