name: Publish Github Pages

on:
  push:
      branches:
        - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: install cli tools
      run: |
        npm install -g --no-save \
          ionic@5.4.15

    - name: npm install
      run: npm install

    - name: build
      run: |
        ionic build \
          -- \
          --base-href https://enteee.github.io/count/
      env:
        CI: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./www
